### ISSUE TITLE
Add newest modules

### ISSUE THREAD

**Issue by nnbveh** [spectromas/NYSTHI-Dark-Theme#1]
Hi! Just found your pack, amazing, now these little modules don't stand out as much, makes me calmer...:)

Could you add the recent modules too maybe? Would be fantastic!
<img width="1113" alt="Screen Shot 2020-10-29 at 15 54 19" src="https://user-images.githubusercontent.com/39271290/97576447-244dec80-1a29-11eb-8f7d-fbf3e7c72e8e.png">

**Comment by spectromas** [comment]
Hey, I'm glad to hear that you like the skin! 

I've just updated the files so see what you think. I've added another zip called NYSTHI_EXTRAS, the contents of that will need to be added to the default (res) folder overwriting the existing files. These modules, for some reason, are not picked up from the res_user folder. I will write a bug report to request that to be fixed but for now just overwrite the originals. 

Let me know if there is anything that I've missed or you think could be improved.
